eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: order
  datasource:
    username: root
    password: 123zou
    url: jdbc:mysql://127.0.0.1/product?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

PRODUCT:
  ribbon:
    NFloadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

server:
  port: 8081
  
env:
  test1
