spring:
  application:
    name: order
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.31.115:3306/product?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest  

PRODUCT:
  ribbon:
    NFloadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    
server:
  port: 8080
  
env:
  dev
