spring:
  datasource:
    username: root
    password: 123zou
    url: jdbc:mysql://mysql:3306/product?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672  
  redis:
    host: localhost
    port: 6379  
  jpa:
    show-sql: true
