spring:
  datasource:
    username: root
    password: 123zou
    url: jdbc:mysql://127.0.0.1/product?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672  
  jpa:
    show-sql: true
