spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123zou
    url: jdbc:mysql://127.0.0.1/product?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
  redis:
    host: 127.0.0.1
    port: 6379
